#!/bin/env python
from fluidnc_serial import serial_interface
import sys

def main():
    s = serial_interface.SerialInterface(sys.argv[1], "microcontroller")
    while True:
        s.readline()

if __name__ == "__main__":
    main()
